name: Job set up
description: Sets up the Java and Gradle
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: "corretto"
        java-version: "21"

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash
