name: Job set up
description: Sets up the Java and Gradle
inputs:
  perenual_api_key:
    required: true
    description: "perenual api key"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: "corretto"
        java-version: "21"

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash
    - name: Add Koin.Properties
      shell: bash
      run: |
        mkdir -p shared/src/commonMain/resources
        cat <<EOF > shared/src/commonMain/resources/koin.properties
          PERENUAL_API_KEY=$PERENUAL_API_KEY
          EOF
      env:
        PERENUAL_API_KEY: ${{ inputs.perenual_api_key }}
