name: iOS set up
description: Sets up Kotlin Native and Cocoapods
inputs:
  firebase-plist:
    description: 'Base64 encoded Firebase plist'
    required: true
runs:
  using: "composite"
  steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - shell: bash
      run: ./gradlew linkDebugFrameworkIosArm64 linkDebugFrameworkIosArm64

    - name: Create Firebase Plist
      shell: bash
      run: |
        echo "$FIREBASE_PLIST" | base64 --decode > iosApp/GoogleService-Info.plist
        if ! plutil -lint iosApp/GoogleService-Info.plist; then
          echo "Error: Invalid plist file generated"
          exit 1
        fi
        echo "GoogleService-Info.plist created successfully"
      env:
        FIREBASE_PLIST: ${{ inputs.firebase-plist }}
