name: iOS set up
description: Sets up Kotlin Native and Cocoapods
runs:
  using: "composite"
  steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - shell: bash
      run: ./gradlew linkDebugFrameworkIosArm64 linkDebugFrameworkIosArm64
#    - shell: bash
#      name: Install Dependencies
#      run: |
#        cd iosApp
#        pod install --verbose