name: iOS set up
description: Sets up Kotlin Native and Cocoapods
inputs:
  firebase-plist:
    description: 'Base64 encoded Firebase plist'
    required: true
runs:
  using: "composite"
  steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'
    - shell: bash
      run: ./gradlew linkDebugFrameworkIosArm64 linkDebugFrameworkIosArm64

    - name: Create Firebase Plist
      shell: bash
      run: |
        echo "$FIREBASE_PLIST" > iosApp/GoogleService-Info.plist.b64
        base64 -d -i iosApp/GoogleService-Info.plist.b64 > iosApp/GoogleService-Info.plist
      env:
        FIREBASE_PLIST: ${{ inputs.firebase-plist }}
